Módulo 1 - Guilherme Moreira
guifabrin/eldorado_mentoria_web pull request #9
Opened 2022-06-13 16:30 UTC by gfmoreira

Pagina do desafio do modulo_01  da mentoria web.

2022-06-15 18:12 UTC, refuri commented on modulo_1/index.html
> +        -->
Seções comentadas podem ser removidas para deixar o código mais limpo e melhor de entender.

2022-06-15 19:40 UTC, guifabrin reviewed
A estrutura deve ser docs/guilherme.moreira/modulo_1

2022-06-15 19:40 UTC, guifabrin commented on modulo_1/assets/css/srcBar.css
> +}
Nit. utilizar TAG como nome de classe. E escolher se utilizará Inglês, ou pt.

2022-06-15 19:40 UTC, guifabrin commented on modulo_1/assets/css/srcInf.css
> +    text-align: center;
```
.srcInf__information__userCompany, .srcInf__information__userFollow ...
```

2022-06-15 19:40 UTC, guifabrin commented on modulo_1/assets/css/srcInf.css
> +        width: 120px;
Tentar utilizar uma porcentagem.

2022-06-15 19:40 UTC, guifabrin commented on modulo_1/assets/css/style.css
> +.containerTeste{
Nit. Teste

2022-06-15 19:40 UTC, guifabrin commented on modulo_1/assets/js/script.js
> +    return {profileResult, profileRepos};
Separar o fetch do profile e dos repos.

```
getProfileUser(username){
    return fetch(`${url}/${user}`).then(response=>response.json())
}
```


```
getUserRepos(username){
    return fetch(`${url}/${user}/repos`).then(response=>response.json())
}
```

2022-06-15 19:40 UTC, guifabrin commented on modulo_1/assets/js/script.js
> +</section>`;
Formatar para deixar numa estrutura legivel.

2022-06-15 19:40 UTC, guifabrin commented on modulo_1/assets/js/script.js
> +    repos.forEach(repo =>{
Recomendo utilizar o map.
```
let output = '';
['teste', 'guilherme'].forEach(item=>{output+=`${item}<tag>`});


['teste', 'guilherme'].map(item=>{return `${item}<tag>`}).join('')
```

2022-06-15 19:40 UTC, guifabrin commented on modulo_1/assets/js/script.js
> +search__id.addEventListener("keyup", (e) => {
sugiro utilizar o onkeyup atributo no html

2022-06-15 19:40 UTC, guifabrin commented on modulo_1/assets/js/script.js
> +search__id.addEventListener("keyup", (e) => {
utilizar event ao invés de e

2022-06-15 19:40 UTC, guifabrin commented on modulo_1/assets/js/script.js
> +        })
getUserProfile(user).then(showProfile).then(
    () => getUserRepos(user).then(showRepos)
).catch((erro) => mostrarErro())

getUserProfile(user).then(showProfile).catch((erro) => mostrarErro())
getUserRepos(user).then(showRepos).catch((erro) => mostrarErro())

2022-06-15 19:40 UTC, guifabrin commented on modulo_1/index.html
> +    <link rel="stylesheet" href="assets/css/srcBar.css">
Utilizar ./assets/

2022-06-15 19:40 UTC, guifabrin commented on modulo_1/index.html
> +<body class="containerTeste">
Temos apenas um `body` então nao precisamos de classe.

2022-06-15 19:40 UTC, guifabrin commented on modulo_1/index.html
> +        -->
Remover comentários.

2022-06-29 15:18 UTC, SantanaC4 commented on modulo_1/index.html
> +<section class="userInformation">
**Dica:**
**Difference between 'section' and 'div' in 'aside' sidebar**
https://stackoverflow.com/questions/39232773/difference-between-section-and-div-in-aside-sidebar

2022-06-29 17:58 UTC, refuri commented on modulo_1/assets/js/script.js
> +searchId.addEventListener("keypress", (event) => {
Sugestão: Utilizar o <form> :
https://www.w3schools.com/html/html_forms.asp

2022-06-29 17:58 UTC, refuri approved these changes

2022-06-29 19:08 UTC, guifabrin commented
@gfmoreira atualizar a branch e resolver o conflito.

2022-06-29 19:09 UTC, guifabrin commented on modulo_1/assets/js/script.js
> +const profileResult = document.querySelector('.information');
Se somente existir um information utilizar id ao invés de classe.

2022-06-29 19:23 UTC, guifabrin requested changes

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/assets/js/script.js
> +const profileRepos = document.querySelector('.repositories');
Se somente existir um repositories utilizar id ao invés de classe.

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/assets/js/script.js
> +    )
Identação.

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/assets/js/script.js
> +    )
Identação.

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/assets/js/script.js
> +                <img src="${user.avatar_url}" alt="">
alt vazio, precisa identificar para melhorar questões de SEO

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/assets/js/script.js
> +searchId.addEventListener("keypress", (event) => {
Neste caso é melhor utilizar ou o form como @refuri falou ou utilizar o onkeypress diretamente no HTML.

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/assets/js/script.js
> +    if (event.keyCode == 13) {
Não usar numeros mágicos.

A pergunta é: O que é 13?
Você pode dizer algo como:

```
const KEY_CODE_ENTER = 13
if (event.keyCode == KEY_CODE_ENTER ) {
}
```

Outra questão é utilizar guard clause para evitar chegar no código abaixo:

```
if (!event.keyCode == 13) return
getProfileUser(user).then(showProfile).catch((error) => mostrarError());
getUserRepos(user).then(showRepos).catch((error) => mostrarError());
```

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/assets/js/script.js
> +        getProfileUser(user).then(showProfile).catch((error) => mostrarError());
mostrarError utiliza duas linguagens, como estás a utilizar o ingles sugiro showError()

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/index.html
> +        <img src="./assets/img/gitsearch_2.png" alt="">
alt vazio prejudica SEO.
Padronizar as nomeclaturas das imagens pode ajudar a identificar o que é cada uma.

2022-06-29 19:23 UTC, guifabrin commented on modulo_3/README.md
> -# Mentoria WEB - Módulo 3
Desfazer essa alteração.

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/assets/css/personalInformation.css
> +.btn {
btn não é um nome de classe bom e está sendo usado em dois níveis hierarquicos:
![image](https://user-images.githubusercontent.com/30579757/176518091-e64951cd-baf4-48f4-9217-6433d6835450.png)

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/assets/css/personalInformation.css
> +.btn:hover {
Ótima utilização de transition!

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/assets/css/personalInformation.css
> +    height: 90%;
utilizar calc ao height juntamente com o padding.

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/assets/css/personalInformation.css
> +    padding-top: .2em;
É uma boa pratica definir a medida como padrão: px, rem, em, %, eu particularmente gosto de % e em

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/assets/css/personalInformation.css
> +}
Muito bom!

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/assets/css/personalInformation.css
> +        width: 100px;
Algumas dessas informações não são necessárias pois não são alteradas em uma tela maior, revisar.

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/assets/css/personalRepositories.css
> +}
Color pode ser reaproveitada.

2022-06-29 19:23 UTC, guifabrin commented on modulo_1/assets/css/searchBar.css
> +.form {
Se existe apenas um form utilizar apenas a tag como identificador css

2022-06-29 19:25 UTC, guifabrin commented
@SantanaC4 e @refuri, depois que o @gfmoreira corrigir façam um novo code review e neste momento verifiquem nos meus comentários o que vocês deixaram passar, ok?

2022-06-30 17:13 UTC, gfmoreira commented on modulo_1/assets/css/personalInformation.css
> +    height: 550px;
acabei removendo o seletor, esta se comportando de acordo com o esperado sem.

2022-07-01 16:53 UTC, pinhak2 commented on modulo_1/assets/css/personalInformation.css
> +    content: "";
content eh obrigatorio? esta vazio.

2022-07-01 16:54 UTC, pinhak2 commented on modulo_1/assets/css/personalRepositories.css
> +
Trocar px para %?

2022-07-08 13:23 UTC, FrancieleFranco approved these changes

2022-07-13 16:06 UTC, pinhak2 approved these changes

2022-07-18 16:48 UTC, guifabrin approved these changes

2022-07-18 18:00 UTC, merged